### ISSUE TITLE
[enhancement] Add an option to check user access

### ISSUE THREAD

**Issue by CaledoniaProject** [p0dalirius/FindUncommonShares#10]
Can you also check whether it's readable anonymously or accessible by current user?

**Comment by p0dalirius** [comment]
Yes, I'll add this check

It will be a good step towards implementing #5

**Comment by CaledoniaProject** [comment]
FYI: nmap will show whether the current user has read access, read-write access or no access

**Comment by CaledoniaProject** [comment]
Can you implement something simple first? e.g just check if the user has access to the shares is good enough.
This looks quite much like it: https://github.com/fortra/impacket/blob/master/examples/smbclient.py#L98

Just do a login and catch the exception.

**Comment by CaledoniaProject** [comment]
This should work: https://github.com/fortra/impacket/issues/1521#issuecomment-1506907276

**Comment by p0dalirius** [comment]
Implemented in https://github.com/p0dalirius/FindUncommonShares/commit/fcd7508b83f14e9dbea5f2f20e6bb50a58dd33cc with option `--check-user-access` :

Example with a domain user and as domain admin:

![image](https://user-images.githubusercontent.com/79218792/232128264-d469632f-863b-4055-ac10-925f054ce582.png)
