### ISSUE TITLE
[enhancement] Use parse_target instead of -u, -p and -d

### ISSUE THREAD

**Issue by CaledoniaProject** [p0dalirius/FindUncommonShares#13]
Can you take a look at this? https://github.com/fortra/impacket/blob/master/examples/smbexec.py#L378

All impacket scripts use something like `user:pass@domain` to specify the clear-text credentials, but your script splits it into 3 arguments.

**Comment by CaledoniaProject** [comment]
https://github.com/fortra/impacket/blob/master/impacket/examples/utils.py#L26

**Comment by p0dalirius** [comment]
Hi,

Yes I am aware of this. I prefer the `-u -p -d` format for its clarity instead of the impacket `DOMAIN/user:P@ssw0rd123!@192.168.1.71` format. I do not plan to change it in FindUncommonShares.

Best regards,
