### ISSUE TITLE
[enhancement] Implement "writable" in access_rights

### ISSUE THREAD

**Issue by CaledoniaProject** [p0dalirius/FindUncommonShares#14]
Can you take a look at this one and add a "writable" access check?
https://github.com/Porchetta-Industries/CrackMapExec/blob/master/cme/protocols/smb.py#L734

**Comment by p0dalirius** [comment]
Implemented in https://github.com/p0dalirius/FindUncommonShares/commit/a48a0a5d972e792236754cd5ce8f1d39202de751

![image](https://user-images.githubusercontent.com/79218792/232181280-6f971209-c573-4031-8ef3-8ebdb9cb6460.png)
