### ISSUE TITLE
[enhancement] Add an option to filter access rights

### ISSUE THREAD

**Issue by CaledoniaProject** [p0dalirius/FindUncommonShares#16]
Can you add an option to filter access rights? e.g `--readable` / `--writable`

**Comment by p0dalirius** [comment]
Implemented in https://github.com/p0dalirius/FindUncommonShares/commit/954ac30adf3d7f24e35f7fd2e97e8d982ab6adda

![image](https://user-images.githubusercontent.com/79218792/232253507-f201b11c-f2ed-4ebd-a2f6-e7fa00714b98.png)
![image](https://user-images.githubusercontent.com/79218792/232253521-bcabc386-425b-4d69-9fb8-fee099e7c423.png)
