### ISSUE TITLE
[bug] Unable to authenticate using a NT hash

### ISSUE THREAD

**Issue by jsdhasfedssad** [p0dalirius/FindUncommonShares#17]
Hi,

Thank you for this tool!

I am trying to authenticate using a NT hash but for unknown reasons I am unable to format my command in a way this tool accepts. I have tried different syntax but so far none works. Including the one that is outputted in the the error message (which does not make sence). What is the correct syntax? If this is a bug, perhaps Kerberos authentication should be verified as well.

![shares1](https://user-images.githubusercontent.com/97032878/234258301-20d1bcc3-648f-450c-b313-8351e804becd.png)

**Comment by jsdhasfedssad** [comment]
You were right about the short hash. However, after correcting that I still have issues. 

As you can see below authenticating to LDAP  using the same account and NT hash to the same target using CrackMapExec works. Using the same account but using it's plaintext password in combination with FindUncommonShares works. But, using the same account and it's NT hash with FindUncommonShares fails.

![shares2](https://user-images.githubusercontent.com/97032878/234285651-90765ad9-6619-4c18-8070-b328e07d5232.png)

**Comment by p0dalirius** [comment]
Yes I had that too I need to fix that

Please add a `:` in front of the hash for the moment, like this `-H :fc525c9683e8fe067095ba2ddc97188d`

**Comment by jsdhasfedssad** [comment]
Hi again,

Today I cloned main in order to test this fix. Now authenticating using a NT hash works but using a plaintext password does not. The opposite to before the fix.

![shares3](https://user-images.githubusercontent.com/97032878/236842668-e3ca1228-a82d-4306-8910-157c6f0f251e.png)

**Comment by p0dalirius** [comment]
Hi @jsdhasfedssad, I've fixed it :)
