### ISSUE TITLE
[enhancement] Change colors of output

### ISSUE THREAD

**Issue by pedroflor** [p0dalirius/FindUncommonShares#20]
Hi!
I'll like to suggest changing slightly the color schema for the access types:

access: $\color[rgb]{1,0,0} WRITE$
access: $\color[rgb]{0,1,0} READ$
access: $\color[rgb]{1,1,0} DENIED$

I you like, I can make the changes and submit a pull request.

**Comment by p0dalirius** [comment]
Hi,

I understand your proposal. The current colors are chosen to reflect the access we have from an attacker standpoint. It is, in my opinion, more easily readable during pentest engagements.

Best regards,
