### ISSUE TITLE
[bug] Output File Doesn't Respect Flags

### ISSUE THREAD

**Issue by xybytes** [p0dalirius/FindUncommonShares#21]
When using certain flags, such as `--ignore-hidden-shares` or `--readable`, the exported output file does not seem to adhere to the specified filters. For instance, as demonstrated in the attached image, despite activating the `--ignore-hidden-shares` and `--readable` flags, the output includes all shares. This includes shares to which I lack read access, and hidden shares like `C$`. Is this the intended behavior?

![share01](https://github.com/p0dalirius/FindUncommonShares/assets/49211005/2438526c-0aa9-4178-947a-c401d9c28ae4)

![share02](https://github.com/p0dalirius/FindUncommonShares/assets/49211005/0d1cac06-4df7-4d11-a32f-cde09ae3e7ec)

**Comment by p0dalirius** [comment]
Hi!
Yes it was the intended behavior, but I can change it. I chose this implementation so that you can still filter all the results with the table headers in Excel. But you are right it would be better with filters applied, I will be implementing it
