### ISSUE TITLE
[bug] Issue when attempting to run with password authentication

### ISSUE THREAD

**Issue by juanhundo** [p0dalirius/FindUncommonShares#26]
Running `FindUncommonShares.py` with password-based authentication results in an authentication invalid error due to the logic in the `sectools/windows/ldap.py` library. Currently, the condition check on line 169 of the `ldap.py` library gets triggered when no hashes are supplied to `FindUncommonShares.py` because the `nthash` and `lmhash` variables are passed as empty strings instead of 'None' type.

![error](https://github.com/p0dalirius/FindUncommonShares/assets/1903524/e3cc6669-4e9d-4e76-9e2e-a575b4dd26ce)

Removing the condition checks for `nthash is not None` and `lmhash is not None` in line 169 of the `ldap.py` library resolves the issue but I'm not sure if these conditions should be kept.

Running `FindUncommonShares.py` after removing the two conditional checks mentioned above results in the tool running as expected.

![success](https://github.com/p0dalirius/FindUncommonShares/assets/1903524/a309605d-9f27-4f82-9c85-8a57bbb31fce)

**Comment by juanhundo** [comment]
I submitted a PR for the `sectools` repo here: https://github.com/p0dalirius/sectools/pull/7

**Comment by p0dalirius** [comment]
Hi,

I'm sorry, I tried to fix something yesterday and broke things instead

Thank you for the fix
