### ISSUE TITLE
[enhancement] Add support of custom dns server instead of the DC

### ISSUE THREAD

**Issue by CaledoniaProject** [p0dalirius/FindUncommonShares#9]
Can you an argument to support custom dnsserver instead of dc-ip? Also, please print something when DNS resolve failed. Right now I had to modify the script to make it work.

**Comment by CaledoniaProject** [comment]
Also, please print something when DNS resolve failed.

**Comment by p0dalirius** [comment]
Good point, I'll add an option and debug info for this :)

**Comment by p0dalirius** [comment]
Implemented option in https://github.com/p0dalirius/FindUncommonShares/commit/38f05d53ee92079113b2b0eb894c7c589b1e51aa: 

```
  -ns NAMESERVER, --nameserver NAMESERVER
                        IP of the DNS server to use, instead of the --dc-ip.
```

Example usage:

```
$ ./FindUncommonShares.py -u Administrator -p 'Admin123!' -d LAB.local --dc-ip 192.168.1.71 --show-share C$ --nameserver 192.168.1.21 
FindUncommonShares v2.5 - by @podalirius_

[>] Extracting all computers ...
[+] Found 2 computers in the domain. 

[>] Enumerating shares ...
[>] Found 'C$' on 'TDC01.DOMAIN.local' (comment: 'Default share')

```
